use crate::ModuleResult;
use std::fmt::Write;
use std::path::Path;

pub fn write_html(path: &Path, modules: &[ModuleResult]) -> Result<(), String> {
    let mut rows = String::new();
    for module in modules {
        let _ = write!(
            rows,
            "<tr><th>{}</th><td>{}</td></tr>",
            escape_html(&module.key),
            escape_html(&module.value)
        );
    }
    let generated = crate::util::now_epoch_seconds();
    let html = format!(
        "<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>femfetch report</title><style>body{{margin:0;background:#171521;color:#f5f5ff;font:16px system-ui,sans-serif}}main{{max-width:760px;margin:4rem auto;padding:2rem}}h1{{color:#cbbdff}}table{{width:100%;border-collapse:collapse;background:#211e2e;border-radius:12px;overflow:hidden}}th,td{{padding:.75rem 1rem;text-align:left;border-bottom:1px solid #38334a}}th{{color:#ffd1e3;width:32%}}footer{{color:#aaa4bc;margin-top:1rem;font-size:.875rem}}@media(max-width:600px){{main{{margin:0;padding:1rem}}th,td{{display:block;width:auto}}th{{padding-bottom:0;border:0}}}}</style></head><body><main><h1>femfetch system report</h1><table>{rows}</table><footer>Generated by femfetch {} · Unix timestamp {generated}</footer></main></body></html>\n",
        env!("CARGO_PKG_VERSION")
    );
    std::fs::write(path, html)
        .map_err(|error| format!("Could not write {}: {error}", path.display()))
}

pub fn escape_html(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '&' => escaped.push_str("&amp;"),
            '<' => escaped.push_str("&lt;"),
            '>' => escaped.push_str("&gt;"),
            '"' => escaped.push_str("&quot;"),
            '\'' => escaped.push_str("&#39;"),
            _ => escaped.push(ch),
        }
    }
    escaped
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn escapes_all_html_sensitive_characters() {
        assert_eq!(escape_html("<&\"'>"), "&lt;&amp;&quot;&#39;&gt;");
    }
}
